name: Ender1
version: 1.6.0
slug: vnc1
panel_icon: fapro:ender1-v3#fullcolor
description: A noVNC client integrated in Home Assistant
url: https://github.com/xcaliber178/Hassio-Addons/tree/main/vnc-viewer-1
ingress: true
ingress_port: 6080
ingress_entry: vnc.html?autoconnect=true
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
boot: manual
hassio_api: true
image: ghcr.io/poeschl/ha-vnc-{arch}
init: false
options:
  vnc_server_host: localhost
schema:
  vnc_server_host: str
  vnc_server_port: int?
  vnc_server_password: str?
